### ISSUE TITLE
Caddyfile: - Parse error: Unknown directive 'radiusauth'

### ISSUE THREAD

**Issue by TimT78** [jamesboswell/caddy-radius#1]
I successfully compiled caddy-radius into caddy for Windows by inserting: _ "github.com/jamesboswell/caddy-radius" in to run.go

But when I try to run caddy, I get the following error: Caddyfile:6 - Parse error: Unknown directive 'radiusauth'

I realize caddy-radius has not been tested on Windows yet, but I was wondering if you saw anything obvious I was doing wrong.  It compiled without issues, but caddy doesn't seem to recognize radiusauth.

My Caddyfile for testing is as follows:
server.domain.local {
	ext .html .htm .php
	root c:\caddy\www	
	gzip
	tls off
	radiusauth {
        	server 192.0.2.10:1812 192.0.2.90:1812
        	secret SuperAWesomeSecret
        	realm  "RADIUS Auth"
        	except /public /assets /images
        	cache  c:\caddy\radiuscache
        	cachetimeout 300
	}
	header / {
		X-Content-Type-Options nosniff
		X-XSS-Protection "1; mode=block"
		Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
	}				
}

**Comment by TimT78** [comment]
Well I figured out what caused the unknown directive.  I had to also add the directive to plugins.go.

I can also confirm that this plugin works on the Windows build of Caddy.  I was able to get it to work using Caddy compiled for Windows x64 authenticating to a Windows NPS server.  So these are two things you can add to confirmed working.

**Comment by jamesboswell** [comment]
Thank for the feedback @TimT78 and apologies for the late repsonse,  I've been away.   Good to see you got it working and on Windows! That's awesome.   

Let me know if you have further issues.
